### ISSUE TITLE
Change Grid Width?

### ISSUE THREAD

**Issue by MayaGans** [budparr/gohugo-theme-ananke#105]
I'm creating my first website and love this theme as a learning tool, but I'm struggling to find where in the style sheet to change the grid width. Specifically, I'd like to have the blog article column wider (so code chunks fit on the page) and the 'related' column a bit narrower. I see there's a way on the tachyon's website [to change the grid width](http://tachyons.io/docs/layout/grid/) but I'm not sure where this code would be inserted.

**Comment by budparr** [comment]
Hi, @MayaGans  You can change the CSS in the src directory, just writing a class to override what you want: https://github.com/budparr/gohugo-theme-ananke/tree/master/src Thanks!

**Comment by rwhitt2049** [comment]
@MayaGans , Did you figure out how to do this? Do you have an example you could share with me?

**Comment by dmakogon** [comment]
@budparr - I've just moved to Hugo, and chose Ananke as my theme - much thanks! Looks like I'm not the only one who was wondering how to increase page width. I see your note above, about "just writing a class" - unfortunately, I have no idea what, exactly, has to be done. Do you have any documentation or hints for accomplishing this? I'm trying to avoid having a very narrow column of content rendered. Thanks again.
