### ISSUE TITLE
Not all config settings included in website build

### ISSUE THREAD

**Issue by Allen616** [budparr/gohugo-theme-ananke#106]
My Google Analytics info provided in my config file is not included in my local or deployed build. I have checked your instructions and that on Hugo.io. It all appears to be consistent.

`title = "Citizen Labs"`
`baseURL = "https://citizenlabs.org"`
`languageCode = "en-us"`
`theme = "ananke"`
`publishDir = "public"`
`MetaDataFormat = "yaml"`
`DefaultContentLanguage = "en"`
`Paginate = 3`
`googleAnalytics = "UA-115392197-1"`
`enableRobotsTXT = true`

Should `MetaDataFormat = "toml"` instead?

Other things like description and keywords are also not included in the builds but other things are.

Thanks

**Comment by Allen616** [comment]
Here is a link to our Repo: https://github.com/citizenlabsgr/homepage

**Comment by Allen616** [comment]
Or could it be that there is a typo in `baseof.html` ?

Pls, see. https://github.com/gohugoio/hugo/commit/06e90b1237cc29fa17be96d13bf9d0428e65e2a8

**Comment by budparr** [comment]
Hi @Allen616 To see the Google Analytics, you need to run your site in production mode. Add this: `HUGO_ENV=production` before your build command. I'll add that to the Readme.

Let me know if that works. And if you want to give me some specifics about the other things you are missing, you can post them here.

**Comment by Money-Samurai** [comment]
Thanks that worked for me, although in windows cmd this doesn't work. 
Saw that this is a Linux command, and when using Git bash in the directory, I could use the command, and Google analytics is now working

**Comment by panmanphil** [comment]
I am having the same problem. I've tried both using `-e production` and the `HUGO_ENV=production` Any other things to look for?

**Comment by regisphilibert** [comment]
@mountainbug95 I think we only need to address documentation here. Could you investigate how to run the production variable under windows and update the documentation with ways to run the site in production environment on several machines?

Thanks a ton!
