### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by boydkelly** [budparr/gohugo-theme-ananke#108]
Will this be coming one day?  It would be awesome addition.  Thanks.

**Comment by jan-xyz** [comment]
I would be interested as well, I'm looking in to this right now. I like that Ananke is really basic and not so bloated like the other themes especially the ones supporting multilingual content. All it needs for me right now is provide a language picker in the menu or side-bar.

I'm trying to figure out how themes and templates work. If you have good resources to look things up, I'd be happy to write a PR. The official documentation is really basic and doesn't really help.

**Comment by jan-xyz** [comment]
I created a [fork](https://github.com/jan-xyz/gohugo-theme-ananke) of your repository and started looking deeper into the theme stuff and it worked :) I also have to row back on my statement that the documentation doesn't help. I mostly copied stuff from the documentation and adjusted it to fit the overall appearance of the theme. It's still WIP but I think it can be helpful for others looking into it. I am also open to other suggestions and would be happy to get this into the main theme!

**Comment by jan-xyz** [comment]
Partial multi language support was merged into master with #144.

@budparr what is your opinion regarding localization of strings? I could implement something like [this](https://gohugo.io/content-management/multilingual/#translation-of-strings) with a PR. I do think, however, that it will be an ongoing effort with adding more localizations in the future.

**Comment by budparr** [comment]
@jan-xyz I'd like to make this a truly multi-lingual theme, so your contribution would be welcome. 

With a little bit of care, it can be multi-lingual without upsetting those who come into the theme with one language. I will chat more about that with @regisphilibert

**Comment by jan-xyz** [comment]
Sounds good. I would suggest to aim for a solution that looks the same as it is right now as a default and everything else is an add-on.

**Comment by jan-xyz** [comment]
@budparr, I think this can be closed now?
