### ISSUE TITLE
Alignment change in new version?

### ISSUE THREAD

**Issue by jenniferthompson** [budparr/gohugo-theme-ananke#111]
Hello, and thank you so much for the theme - I am loving it for my site! I've run into an alignment issue when updating to the latest version, and am not sure how to fix it. I have searched for ideas, but I'm not a developer and I'm very new to CSS, so my apologies if this is a basic question or is covered elsewhere!

I originally built my site just prior to the last Ananke update, and recently updated to the new version. This seems to have changed my index pages from left- to center-aligned, when on desktop with a wide browser window, and I haven't had luck trying to change back to forced left alignment. Per #91, I removed `flex-l` from the two `single.html` files, but this didn't seem to change it; I also tried changing anything `center` in `layouts/` without success.

<img width="948" alt="Pre, post-Ananke update" src="https://user-images.githubusercontent.com/7783352/41260192-0b4f6b8c-6d9c-11e8-840c-02aabc71647e.png">

Examples on my [main site](https://jenthompson.me/resources/) (has not yet been updated) and [staging site](https://infallible-chandrasekhar-02d52e.netlify.com/resources/index.html) (has been updated; Github repo [here](https://github.com/jenniferthompson/webstage)).

Any ideas would be much appreciated - and again, thank you for such a beautiful theme!

**Comment by budparr** [comment]
Hi @jenniferthompson Did you change your content at all. It looks like the resources page had previously used the[ page layout](https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/page/single.html) and now it's using the default layout. If you haven't changed anything, I'm wondering if your local builds for the old version are having the issue (that is, I'm wondering if something changed in Hugo that caused the page to pick up a different layout).

**Comment by jenniferthompson** [comment]
Thanks for the quick response @budparr!

I added a static/slides/ directory and some bullet points to the Resources page; I realized I needed to update the theme when the site wouldn’t build after those edits. No other changes to the content or file structure before seeing the alignment issue. However, with the update, it was also not correctly creating the Resources page as it used to, so I added it back using main.menu in my config.toml, which could explain that difference in layouts. I haven’t been able to figure out why; my directory structure didn’t change other than adding static/slides/ (eg, content/resources/_index.md still existed), so as far as I can tell it should have picked it up. I tried several things there but ended up rebasing the repo; I can detail those if it would be helpful.

**Comment by budparr** [comment]
Perhaps you can send me the link to your repo, and I'll have a look

**Comment by jenniferthompson** [comment]
I realized that I had accidentally pushed `resources/_index.html` to the repo (oops!); removing that took care of the Resources page not being included in the site menus, so the only issue I'm having is the alignment. Here are the relevant links:

- Staging site: This is the one which reflects the updated version of Ananke, as well as the alignment issues.
    - Repo: [/webstage](https://github.com/jenniferthompson/webstage)
    - [Actual site](https://infallible-chandrasekhar-02d52e.netlify.com/)
- Main site: This repo has not been updated since Ananke was updated; it reflects the code for pages that were all left-aligned with the previous version of Ananke (as well as an older version of Hugo).
    - Repo: [/website](https://github.com/jenniferthompson/website)
    - [Actual site](https://jenthompson.me)

**Things I've tried**
- Removed from `themes/.../layouts` every instance of `flex-l` except for `partials/site-navigation.html`
- Building with both Hugo 0.32 (what I was using previously) and Hugo 0.41
- In the `/webstage` repo, I had made an additional `/layouts/` directory to change all fonts to Avenir, but I've removed it for now to make sure they weren't the problem.
    _(In the main repo, I did this directly in the theme files, but was recently advised to do it separately so that I wouldn't have to do it again when the theme gets updated.)_ 

So far the pages are still center-aligned when the browser is wide enough. This is observed on the [About](https://infallible-chandrasekhar-02d52e.netlify.com/about/) and [Resources](https://infallible-chandrasekhar-02d52e.netlify.com/resources/) pages.

Thanks so much for taking a look!

**Comment by budparr** [comment]
Try removing `tc-l` from this line: https://github.com/jenniferthompson/webstage/blob/master/themes/gohugo-theme-ananke/layouts/_default/list.html#L3

I can't do it for you, because you're not using a submodule, but if you let me know if that works I can change it on my master too. I don't recall why that class is there.

**Comment by jenniferthompson** [comment]
Yes, that seems to have done it! Thank you!!

[link to updated Resources page](https://infallible-chandrasekhar-02d52e.netlify.com/resources/)
