### ISSUE TITLE
Twitter featured images support 

### ISSUE THREAD

**Issue by MicZet** [budparr/gohugo-theme-ananke#112]
Hello
first of all - thanks for great work!

I have a question - when i share urls for my posts on Twitter - there is no featured image included - only generic empty template (Opengraph is responsible)?
is it supported in the theme? 

all best,
Michael

**Comment by budparr** [comment]
Hi, @MicZet We are using Hugo's built-ins for open graph and other social networks. They will pick up any posts with an `images` front matter. Keep in mind, they have to be an array, so in your front matter, for example,

```
images:
 - /uploads/image.jpg
```

**Comment by jenniferthompson** [comment]
Hello! I've tried to follow the example above to get Twitter cards working, but the Twitter card validator is giving me errors due (it says) to robots.txt.

<img width="978" alt="screen shot 2018-06-14 at 6 39 05 pm" src="https://user-images.githubusercontent.com/7783352/41443471-b11b9956-7002-11e8-8bed-f540fd59812e.png">

My front matter currently looks like this, per the instructions above:

```
---
title: "About"
description: "Hi. It's good to meet you."
featured_image: '/images/Drottninggatan.jpg'
images:
 - /images/Drottninggatan.jpg
---
```

Should I disable robots.txt for this to work?
