### ISSUE TITLE
Zero article padding in mobile mode

### ISSUE THREAD

**Issue by daniele-athome** [budparr/gohugo-theme-ananke#115]
In Firefox 59 and Chrome (Opera 52) in mobile mode (just resize the window to a mobile width), the `<article>` section has no padding at all. As you might already know, this has impacts on people focusing on the content. Since I'm no publishing expert I don't know the exact padding to use, but if you tell me how much, I can create a pull request for the CSS.

Branch: master (89c26174a48f786f728c57d78fa53ffc100389c0)

![hugo_theme_nopadding](https://user-images.githubusercontent.com/3763726/42423850-acc6c35a-8301-11e8-9be8-06362d079351.jpg)

**Comment by budparr** [comment]
Not sure how this slipped by, but thank you for pointing it out, @daniele-athome.
