### ISSUE TITLE
How to remove the "darkening" of the background image

### ISSUE THREAD

**Issue by Jimmy99** [budparr/gohugo-theme-ananke#117]
This issue is posted for information purposes.
I asked Bud about how to remove the "darkening" of the background image. Bud explained that it is necessary to remove the following line in the file site-header.html in the partials folder of layouts.
Just a word of caution, if your background image is mostly white, because the site title colour is white it might not look so good after making this edit. (I suspect this is why the image is darkened to begin with)

**Comment by apbran2** [comment]
Thanks.

**Comment by acuvic** [comment]
@Jimmy99 - Rather than removing the whole line (which will break the div nesting), just replace the line with a plain <div>?

**Comment by Jimmy99** [comment]
> @Jimmy99 - Rather than removing the whole line (which will break the div nesting), just replace the line with a plain `<div>`?

When I fixed this I remember deleting the line. Perhaps the code has been updated since then requiring the line to be replaced with a plain <div>?

**Comment by budparr** [comment]
If you update the theme code, you should fork it, not update the clone. You won't get updates that way, but your changes will stay in-tact. 

I'll close this, but it will still be here for others to find. Thanks!
