### ISSUE TITLE
 Long urls or links extend beyond content and overlap sidebar

### ISSUE THREAD

**Issue by waroo** [budparr/gohugo-theme-ananke#118]
If you have a really long url or link it will extend beyond the border for the main content instead of wrapping. If you have a sidebar it will overlap the sidebar content. As an example see the links at the bottom of the following page https://kitefaster.com/2017/05/22/create-today-widget-ios-app-swift/

It looks like the header and main tags are set to different widths in the CSS.

**Comment by regisphilibert** [comment]
@mountainbug95 could you take a look at this one?
