### ISSUE TITLE
spread out footer icons

### ISSUE THREAD

**Issue by hemanth7787** [budparr/gohugo-theme-ananke#127]
https://github.com/budparr/gohugo-theme-ananke/blob/8c1280c2a3f2fe9b7df4930cb77f48e27735bd21/layouts/partials/site-footer.html#L2

![screenshot_20180831_165725](https://user-images.githubusercontent.com/2316704/44910160-d00f2b00-ad3f-11e8-8489-8d95d3be5bcc.png)

with ` justify-between` removed
![screenshot_20180831_165812](https://user-images.githubusercontent.com/2316704/44910164-d2718500-ad3f-11e8-80f9-cf92f81033c3.png)

**Comment by budparr** [comment]
Thanks for pointing that out, @hemanth7787 That class was meant to be around the footer items themselves, so rather than removing it, I used a div to apply it correctly.
