### ISSUE TITLE
How can I add MathJax support to my site using the Ananke theme? 

### ISSUE THREAD

**Issue by jasikpark** [budparr/gohugo-theme-ananke#129]
The Hugo documentation says to put 
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```
in a partial layout that will appear on every page that you need the mathjax, but I can't figure out how to make this repository a submodule and at the same time add mathjax support.

**Comment by budparr** [comment]
Hey, @jasikpark You can duplicate this file into the root layouts folder of your project and add the script there. https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/partials/site-scripts.html

**Comment by jasikpark** [comment]
You mean put it in /layouts? Thanks!


-- 
Caleb Jasik
calebjasik@jasik.xyz
https://jasik.xyz
281.614.9841

On September 3, 2018 at 10:43:44 AM, Bud Parr (notifications@github.com) wrote:

Closed #129.

**Comment by budparr** [comment]
yep

**Comment by budparr** [comment]
But it needs to be along the same path, so 

current:
`/themes/gohugo-theme-ananke/layouts/partials/site-scripts.html`

new:

`/layouts/partials/site-scripts.html`

**Comment by jasikpark** [comment]
ah, that's what I was wondering.

**Comment by jasikpark** [comment]
```
{{ $script := .Site.Data.webpack_assets.app }}
{{ with $script.js }}
  <script src="{{ relURL (printf "%s%s" "dist/" .) }}"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
{{ end }}
```

**Comment by KunikaValecha** [comment]
> Hey, @jasikpark You can duplicate this file into the root layouts folder of your project and add the script there. https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/partials/site-scripts.html

This link seems to be broken, can you please resolve the problem in accordance with newer version

**Comment by benslack19** [comment]
I'd like to echo the support for updated MathJax documentation with this theme.

**Comment by KunikaValecha** [comment]
@benslack19  adding the link to mathjax in footer.html worked for me. What is the issue you are facing?

**Comment by benslack19** [comment]
I appreciate your response @KunikaValecha. The version of the ananke theme I just downloaded didn't have a `footer.html` file but it had a`site-footer.html` file in the `partials` folder. These are the different things I've tried but each didn't render the MathJax text correctly.
- Put the MathJax script snippet at the bottom of the `site-footer.html` file in the `partials` folder of the theme (`themes/ananke/layouts/partials`)
- Copying the `site-footer.html` file with the MathJax script snippet and placing a copy in my site's `/layouts/partials` (I'm just playing around with the quick start version.)
- Renaming `site-footer.html` to `footer.html`.

Do you have a repo with the `footer.html` file that I can look at?

**Comment by KunikaValecha** [comment]
@benslack19 you are in right direction. I also added the link in site-footer.html. You won't require any further step that you have done. Just add the link to site-footer.html and you are good to go.

**Comment by benslack19** [comment]
Thank you so much @KunikaValecha. I'm getting closer after realizing my initial error. I was trying different things, but I was using an old markdown file that only contained inline MathJax examples. I see that it works when it's not inline.

On that note, did you try and have success with the solution for handling inline code and mathjax underscores (subscripts)?

**Comment by KunikaValecha** [comment]
For subscript I did it, \\(word_{subscript}\\). What do you mean by inline? Inserting mathematical sign in the line of text?

**Comment by KunikaValecha** [comment]
@benslack19 writing any code in \\( math \\) will keep math in text. PS, that's a double backslash.

**Comment by benslack19** [comment]
Ah okay thank you @KunikaValecha and thank you for clarifying the double backslash is used there. I was using a single dollar sign for my in-line math (which was working on my Jekyll-based site) but I see [here](http://docs.mathjax.org/en/latest/basic/mathematics.html) that that's now discouraged practice. Thanks for your help!

**Comment by acgetchell** [comment]
This doesn't seem to work anymore:

https://github.com/acgetchell/blog/blob/master/layouts/partials/site-scripts.html
