### ISSUE TITLE
Only include menu-contextual if non-empty

### ISSUE THREAD

**Issue by blueyed** [budparr/gohugo-theme-ananke#130]
I was confused about the white / blank space on the right for when there is no TOC / related pages.

Code: https://github.com/budparr/gohugo-theme-ananke/blob/7a32e28d4b239a279ba0415bd26f93f5ced5128c/layouts/_default/single.html#L34-L36

Is it possible to skip the `<aside>` block complete if it is empty / only contains whitespace?

**Comment by blueyed** [comment]
There's also a CSS issue in this regard: below a width of 960px the aside appears to be below, but between 960-1020px the left and right padding is missing:

![2018-09-10-175716_1005x618_escrotum](https://user-images.githubusercontent.com/9766/45309122-46bbdd80-b523-11e8-83fb-7ba74026d2c9.png)

**Comment by budparr** [comment]
Hi @blueyed For the first issue, I believe that was my intent. That is, I would not want the line length to be really wide no matter what is on the page. I fixed the second issue and it's in the latest release. Thanks for your patience!
