### ISSUE TITLE
Limiting the summary using Rmarkdown

### ISSUE THREAD

**Issue by astronomerforfun** [budparr/gohugo-theme-ananke#136]
Summary is too long for me.  Is there a way to use like ten words?  

Great site by the way.  My first one and I enjoy it a bunch.  

Regards,

cs

**Comment by budparr** [comment]
You can make your own summary with `.Content | truncate n`

**Comment by perigee** [comment]
@budparr any chance that u can refer me the line I need to change, sorry not a frontend developer :( Thank you in advance.

**Comment by DanRoscigno** [comment]
@astronomerforfun @perigee : I am specifying the summary in my frontmatter now:

```md
---
summary: "all of the text that I want to show on the blog list page. I am putting it here because I could not figure out how to use truncate to limit it to a shorter snippet."
title: "blah"
featured_image: "/images/image.png"
date: 2023-09-22T18:18:26-05:00
draft: false
---
```
