### ISSUE TITLE
Keeping .jpg with the .rmd file?

### ISSUE THREAD

**Issue by astronomerforfun** [budparr/gohugo-theme-ananke#137]
Does anyone know how to keep the images in the post folder (along with .Rmd file)?  In the future if I migrate to another website for whatever reason I don't want to have to match up all my images with their respective folders.  Any help or hack would be great.  Thanks!

**Comment by budparr** [comment]
Hey, @astronomerforfun See Page Bundles: https://gohugo.io/content-management/page-bundles/#readout 

You'll probably get a faster response to questions like this at the forums. https://discourse.gohugo.io/
