### ISSUE TITLE
single.html Produces Two Main Elements

### ISSUE THREAD

**Issue by ma10** [budparr/gohugo-theme-ananke#149]
layouts/_default/single.html produces two main elements, but there should be only one visible main element in each page, [as the specification says.](https://www.w3.org/TR/html52/grouping-content.html#the-main-element)

With current single.html, the first main element starts before the section title, and the second starts before the content body.

IMO, from the accessibility point of view, the main should start before the content (article) title, and should end after the content body.

**Comment by budparr** [comment]
Thanks, @ma10 Maybe you can show me your repo. The theme itself doesn't duplicate the main element, as you can see in this screenshot.

![screen shot 2019-01-06 at 10 17 12 am](https://user-images.githubusercontent.com/115347/50737929-4d3e2700-119c-11e9-8532-7fc45f9a961a.jpg)

**Comment by ma10** [comment]
Thanks for the response.
Though, please note that I can't tell what the screenshot shows as I'm blind.

Since I don't have it under git, I attach a few files here.

To reproduce the problem, I did:

1. `hugo new site sample`
2. Clone the ananke theme
3. Copy the config.toml from the examplesite and made minimum changes (see att
[config.toml.txt](https://github.com/budparr/gohugo-theme-ananke/files/2733861/config.toml.txt)

[test.markdown.txt](https://github.com/budparr/gohugo-theme-ananke/files/2733898/test.markdown.txt)

[index.html.txt](https://github.com/budparr/gohugo-theme-ananke/files/2733904/index.html.txt)

ached)
4. Create a very simple sample page as `content/post/test.md` (see attached)
5. After generate the pages, look at `public/post/test/index.html` (see attached)

The relevant part from the resulting file below:

`````
    <main class="pb7" role="main">
  <article class="flex-l flex-wrap justify-between mw8 center ph3 ph0-l">
    <header class="mt4 w-100">
      <p class="f6 b helvetica tracked">
        POSTS
      </p>
      <h1 class="f1 athelas mb1">Test</h1>
            <time class="f6 mv4 dib tracked" datetime="2019-01-07T22:35:21&#43;09:00">January 7, 2019</time>      
                </header>
    <main class="nested-copy-line-height lh-copy serif f4 nested-links nested-img mid-gray pr4-l w-two-thirds-l">
<h1 id="testing">testing</h1>
<p>test for the main elements.</p>
<ul class="pa0">
</ul>
<div class="mt6">
      </div>
    </main>
    <aside class="w-30-l mt6-l">
    </aside>
  </article>
    </main>
`````

**Comment by budparr** [comment]
you're right. I fixed this and will have the release out shortly. Thanks!
