### ISSUE TITLE
The action destination of Formspree is no works (http to https)

### ISSUE THREAD

**Issue by fu-sen** [budparr/gohugo-theme-ananke#150]
This problem requires modification of **README.md**.

[**README.md**](https://github.com/budparr/gohugo-theme-ananke/blob/master/README.md) :
```
{{< form-contact action="http://formspree.io/your@email.com" >}}
```
This is simply Formspree disabling **http** communication.
I confirmed the improvement of the form by changing **http** to **https**.

[A Contact Form to Email Service | Formspree](https://formspree.io/)

**Comment by budparr** [comment]
Thanks! Fixed. Will be in the next release.
