### ISSUE TITLE
Windows environment variables are not considered

### ISSUE THREAD

**Issue by fu-sen** [budparr/gohugo-theme-ananke#153]
This command in the README is invalid when using hugo on Windows:
```
HUGO_ENV=production hugo
```
I set some environment variables on Windows, but I could not reflect it.

I analyzed the theme. As a result, I found this workaround:
**config.toml**
```
[params]
  env = "production"
```
It may need to be added to the README.

**Comment by budparr** [comment]
Thank you, @fu-sen Could you do a PR for the README change? Or, just give me the language to put in. I don't use Windows so don't want to mess it up.

**Comment by fu-sen** [comment]
In order to improve the environment variable setting on Windows, it is necessary to modify the source.
But I can not concretely make that source suggestion.

As far as I can clearly improve the way to add this setting. It was added again.

**config.toml**:
```
[params]
  env = "production"
```

It will be useful not only for Windows. 
The theme of adopting this is unusual, and people who encounter this problem will continue to occur.
