### ISSUE TITLE
Safari Reader View lacks content

### ISSUE THREAD

**Issue by mitchejj** [budparr/gohugo-theme-ananke#162]
The ‘Reader View’ built into Safari on both iOS and macOS does not present any content other than title and date. 

An example of expected behavior using the latest post on gohug/news:

![img_0014](https://user-images.githubusercontent.com/156855/53916308-dc967800-402f-11e9-999b-19189f1609f0.png)

What happens using Reader View on the demo’s Chapter VI: Esmeralda post:

![img_0013](https://user-images.githubusercontent.com/156855/53916220-93462880-402f-11e9-89ef-124e5241b902.jpeg)

**Comment by budparr** [comment]
Thanks for reporting this, @mitchejj I'll take care of it here very soon.
