### ISSUE TITLE
themes/content: no such file or directory

### ISSUE THREAD

**Issue by jacobsun** [budparr/gohugo-theme-ananke#164]
Fresh installed hugo and the theme.

run hugo server got this:

```
My_site_path/themes/content: no such file or directory
```

Hugo Static Site Generator v0.54.0-B1A82C61 linux/amd64 BuildDate: 2019-02-01T09:40:34Z

**Comment by budparr** [comment]
Hi @jacobsun Sounds like you may have an issue aside from the theme. Can you please ask your question to the community? https://discourse.gohugo.io/

Thanks!
