### ISSUE TITLE
Blockquote's are not shown

### ISSUE THREAD

**Issue by Money-Samurai** [budparr/gohugo-theme-ananke#169]
Hi, 
I'm just starting with Hugo and the Ananke theme. Thanks first of all for the efforts put into the creation of the theme!

I noticed that using blockquote (> in markdown), results in HTML code <blockquote></blockquote>. The quote is not shown in browsers. 

A similar issue suggests that the html tags should result in <blockquote class="blockquote">

**Comment by Money-Samurai** [comment]
mm...also new at commenting at github :) another try: 

I notice that when using blockquote in markdown, the resulting html is `<blockquote> </blockquote>`
While a similar issue suggests it should be `<blockquote class="blockquote">`

**Comment by budparr** [comment]
Thanks, @Money-Samurai Some of the issues may not be related to blockquote styling, but I did add some styling for them.

**Comment by Money-Samurai** [comment]
Thanks budparr! the update works, i cloned the latest version and quotes are nicely shown now in the built site 

> (with a line to the left of the quote)
