### ISSUE TITLE
partialCached should not be applied to site-navigation.html

### ISSUE THREAD

**Issue by phy25** [budparr/gohugo-theme-ananke#173]
This bug is introduced by #165. `site-navigation.html` includes `i18nlist.html`, which is different on every page and should never be cached across pages. This will cause bug that i18n links point to other pages rather than this page.

https://github.com/budparr/gohugo-theme-ananke/blob/389e12c252a4586e925424de5ef039f382e9d18a/layouts/partials/site-navigation.html#L7

If you need a patch I can create one, but it should be very simple and involves `layouts/partials/page-header.html` and `layouts/partials/site-header.html`.

**Comment by echarp** [comment]
I'm looking into it

**Comment by phy25** [comment]
Closed by #174.
