### ISSUE TITLE
Include dev and production css etc

### ISSUE THREAD

**Issue by RickCogley** [budparr/gohugo-theme-ananke#18]
Hi @budparr, this is a nice theme. I like the idea that it's for teaching. People could use that. 

Along that line, one idea is: include both the production zipped assets (css/js) and, an unzipped version, so people can see how it works and the difference b/w a minified/zipped and non-minified.

Regards

**Comment by RickCogley** [comment]
Along these lines, you mention about how to use Tachyons. An explanation of how that's done - perhaps by including its css and another css where you customize - would help people imo.

**Comment by budparr** [comment]
Thanks, @RickCogley Those are good ideas. The source files are in the dev branch, but sounds like you think it would be a good idea to include them in master (as well as output unminified versions for perusal).

**Comment by RickCogley** [comment]
I see. I agree that's what you'd do if you were putting it into production yourself. But it's so well documented internally, it might be worth putting some extra comments and pointers in, to explain what the person needs to do in reality. Like "Original tachyons css from dist. Used minified one in production" kind of showing the user how they should comment one out and the other in?

**Comment by jomazu** [comment]
Hi @budparr, excellent theme, I'm really enjoying it! I have one minor request. The addition/incorporation of the following social icons, which seem to be highly used by most developers and professionals - including myself: 
```
- GitHub
- LinkedIn
- CodePen
```
I added them to the following files, for my cloned project:
```
$ config.toml
$ layouts/partials/svg/social-follow.html
```
However, I cannot get the hover:over results to match yours. I pulled the Dev Branch and added the necessary color fill changes to the `src` folder, but still no luck:
```
$ src/css/_social-icons.css

.facebook, .twitter, .instagram, .youtube, .linkedin, .github, .codepen {
  fill: #BABABA;
}

.linkedin:hover {
  fill: #007bb5;
}

.github:hover {
  fill: #000000;
}

.codepen:hover {
  fill: #000000;
}
```
If possible, could you please provide a brief response about the method or process used to re-build (minify) the source after making such changes? It would be greatly appreciated!

**Comment by jomazu** [comment]
@budparr, please disregard! I figured it out how to re-build the source using yarn and webpack - now everything is working as expected... Thanks

**Comment by budparr** [comment]
Thanks, @jomazu Glad you got it worked out. I think I will move the src into master and add some annotations for others. I really appreciate both of your comments.

**Comment by budparr** [comment]
@RickCogley and @jomazu I've added the src folder with the asset pipeline to master, and a more complete readme in the src folder. That could probably use more comments, and your perspective and suggestions are welcome.

@jomazu I know you've got yours worked out, but I've added an issue to add more social icons for those in the futures. Thanks very much for pointing it out.
