### ISSUE TITLE
Theme demo broken on Hugo Themes Showcase 

### ISSUE THREAD

**Issue by onedrawingperday** [budparr/gohugo-theme-ananke#193]
Hello @budparr 

Currently the Ananke theme's demo does not generate as mentioned in https://github.com/gohugoio/hugoThemes/issues/669#issuecomment-518648215

To fix you need to change [line 11](https://github.com/budparr/gohugo-theme-ananke/blob/master/theme.toml#L11) of `theme.toml` to: `min_version = "0.30.2"`

The `min_version` needs to be a string.

Feel free to close this issue once you do the above.

Thank you.

cc: @digitalcraftsman

**Comment by budparr** [comment]
Thanks for the heads up. I've been traveling, but will take care of this shortly.

**Comment by budparr** [comment]
Fixed in #189 Thanks!
