### ISSUE TITLE
Is there anyway to have Recent Articles on the main page to incorporate articles multiple sections?

### ISSUE THREAD

**Issue by moondra2017** [budparr/gohugo-theme-ananke#194]
I am currently playing around with the theme, and it seems that that only posts from one blog
section are displayed on the first page under Recent <blog header>.

If I have multiple blog-tabs (headers), how would I have it display recent articles from both blogs.
For example "Recent Tech", and then under it "Recent Science"

Thank you so much for a great theme.

**Comment by andresmazzo** [comment]
Would be great this improvement! Actually shows the section with most pages (gohugo rule).
It seems that he have already seen this:
https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/index.html#L5

Maybe an array variable like: `sections_on_recent = ["post", "event"]`. If not specified it continue with the actual rule (compatibility).
Do you accept a PR @budparr ?

**Comment by budparr** [comment]
HI @andresmazzo and @moondra2017 The solution already exists. Just add the sections to `Site.Params.mainSections` in your config file
