### ISSUE TITLE
Add sharing links for the posts

### ISSUE THREAD

**Issue by karuppiah7890** [budparr/gohugo-theme-ananke#198]
Medium has a way to share post to Twitter, Facebook

<img width="231" alt="Screen Shot 2019-08-15 at 11 17 41 AM" src="https://user-images.githubusercontent.com/12808424/63075673-11e4b180-bf50-11e9-91f8-6b86027d879d.png">

It would be great to put such links in hugo blogs too. And we can also let people choose what platforms links they want to show and let them embed their usernames too in the post sharing the blog post. 

Some of the platforms / buttons that I have thought is - Twitter, Facebook, WhatsApp, Copy URL

 If this looks cool, I would like to raise a PR for this 😄

**Comment by budparr** [comment]
Hi @karuppiah7890 I'd certainly be happy to have a PR on this. I think the main requirement is to have it all local (i.e. no outside resources).

**Comment by karuppiah7890** [comment]
You mean no putting links to Twitter's js resource? Is it okay to then copy
it and put it in the code?

**Comment by susodapop** [comment]
Hey @karuppiah7890 - are you still working on this? If not, I'll try my hand at it.

**Comment by karuppiah7890** [comment]
I worked on the twitter part. Then got caught up with other things. Didn't check facebook and whatsapp. You can go ahead and do it 😄

I just have one doubt. For twitter, I used the twitter site and noticed they asked me to use their Js code using a link. Instead it would be downloaded and kept locally in the repo is it? Same for Facebook and WhatsApp ?

**Comment by jan-xyz** [comment]
The Twitter part should be fairly straight forward with: 

http://twitter.com/share?text=we_love_hugo&url=http://gohugo.io&hashtags=hashtag1,hashtag2,hashtag3
(taken from: https://stackoverflow.com/a/20832477/2595410)

**Comment by regisphilibert** [comment]
I think we should have a param to disable the share on individual pages. To disable on all, user will use `cascade`.

Let's limit this to post first.
