### ISSUE TITLE
Add Stackbit

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo-theme-ananke#200]
documented here: 
https://github.com/JugglerX/hugo-serif-theme - Scroll down in the README and you can see the "create with stackbit" button. If possible we'd like to do the same for Ananke. So to do this you need to add a stackbit.yaml with some content models which I've documented here: https://docs.stackbit.com/uniform/

**Comment by susodapop** [comment]
Here's a blog post that should help: https://www.stackbit.com/blog/hugo-stackbit-tutorial/
