### ISSUE TITLE
featured_image from page bundle

### ISSUE THREAD

**Issue by naggie** [budparr/gohugo-theme-ananke#203]
Hi, 

I'm in the process of converting my site to use hugo page bundles. I've managed to update all of the images except the featured image -- referencing an image relative to the page bundle does not appear to work.

Is there any way I can assign a featured image from the page bundle?

Thanks!

**Comment by budparr** [comment]
Hi @naggie that's probably a question for the forums.

**Comment by naggie** [comment]
Ok
