### ISSUE TITLE
Topic tags for blog posts?

### ISSUE THREAD

**Issue by diehl** [budparr/gohugo-theme-ananke#205]
Is there a way to add topic tags to blog posts that can later be leveraged to quickly look at a subset of the posts on the blog corresponding to a particular topic?

**Comment by budparr** [comment]
Yep. See this example post, for example: https://github.com/budparr/gohugo-theme-ananke/blob/master/exampleSite/content/post/chapter-4.md and it's published counterpart: https://gohugo-ananke-theme-demo.netlify.com/post/chapter-4/

**Comment by diehl** [comment]
Thanks @budparr! How about displaying a list of all the tags somewhere on the blog so one can navigate the post collection? Is that an existing option in the theme?
