### ISSUE TITLE
baseof.html

### ISSUE THREAD

**Issue by mbernico** [budparr/gohugo-theme-ananke#207]
Hi, probably a dumb question but I'm stumped.

I'm trying to override `./themes/anake/_default/baseof.html` with `layouts/_default/baseof.html` but it seems to not be working. Changes in `layouts/_default/baseof.html` aren't reflected in the build while changes in the themes baseof.html are. 

According to Hugo's lookup order I think this should work. The doc says:
/layouts/_default/baseof.html
/themes/<THEME>/layouts/_default/baseof.html

What am I doing wrong?

**Comment by budparr** [comment]
Hi @mbernico Sounds like you're doing it right. Can't say more without seeing your code. You'll also get more eyeballs on it by asking in the forums.

**Comment by susodapop** [comment]
I agree with @budparr. Could you post some examples of your code or perhaps fork the repo? I'm curious to look into this.

**Comment by mbernico** [comment]
@budparr @susodapop This was my dumb mistake guys, I'm sorry to bug you. I named the folder _defaults instead of _default and had been staring at it way too long.
