### ISSUE TITLE
error

### ISSUE THREAD

**Issue by arguskao** [budparr/gohugo-theme-ananke#218]
git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke

fatal: not a git repository (or any parent up to mount point /Volumes)

WHY??

**Comment by budparr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/2lYlnU5X/14-test)

**Comment by budparr** [comment]
Hi @arguskao This looks like a local GIt issue to me. Might try to the community forums as there might be some folks there who have encountered this sort of thing before .https://discourse.gohugo.io/
