### ISSUE TITLE
Flexible image display

### ISSUE THREAD

**Issue by peleve** [budparr/gohugo-theme-ananke#234]
I'm working on a document that contains lots of images.  They are of different sizes. What I would like to have is a shortcode that allows me to set the size of an image.  Specifically the height, but I want to keep the aspect ratio of the image. I can't figure out how to do this with your theme. 
I've tried using shortcodes from other themes, but either I can't get them to work or they are working incorrectly.  How could this be done?

Thanks for a nice theme otherwise.

**Comment by budparr** [comment]
Hey, @peleve Have you asked in the forums. I don't think there's anything special about one theme or another in regards to using shortcodes. If you put it in your own folder layouts/shortcodes it should work.

**Comment by cptncrnch** [comment]
I added an image to a page that is also a link:

`[![Image alt text](/images/myimage.gif#target "Image title")](https://www.linktoimage.com)`

The image shows on the page with 100% width being set by `.nested-img img`. Is there a way to override the 100% width setting of `nested-img`? I have tried adding custom css in `/static/css/_styles.css` to target the image but the image is still 100% width.

`img[src*="#target"] {
    width: 147px;
    height: 47px;
}
`

`[params]`
`custom_css = ["css/_styles.css"]`
