### ISSUE TITLE
Add expand shortcode

### ISSUE THREAD

**Issue by agrrh** [budparr/gohugo-theme-ananke#246]
Great theme, thank you!

Sometimes it would be useful to have `expand` shortcode.

https://gohugo.io/templates/shortcode-templates/

**Comment by budparr** [comment]
Hi @agrrh You can add any shortcodes you want to your site, just by adding the the file to your own directory, `/layouts/shortcodes/<SHORTCODE>.html`

**Comment by agrrh** [comment]
I thought this would be useful for other theme users. `expand` seems to be kind of a common feature.

Just to clarify, would it work if I prepare PR or this is something you really don't like to include in a theme?
