### ISSUE TITLE
"omit_header_text: true" ignored in _index.md 

### ISSUE THREAD

**Issue by PNMarano** [budparr/gohugo-theme-ananke#253]
Hi! Does the index page get treated specially in terms of parameters? I ask because it seems `omit_header_text: true` doesn't work in it, but does in other pages. If I put the following exact same content in two files (one of which is _index.html):

```
---
title: HomePage
params.featured_image: false
omit_header_text: true
type: page
---
Some simple text here.
```

The index page insists on having the larger header with the page title in it, while any other file looks more like the contact page in the demo site. (Which is the look I'm going for.) Is there a way to do this without hand-editing the css? Removing the `title` line just ends up with the site name being used instead.

- PaulNM

**Comment by budparr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/6jcJq0Pu/3431-test)

**Comment by regisphilibert** [comment]
See https://github.com/budparr/gohugo-theme-ananke/issues/265#issuecomment-638237225
