### ISSUE TITLE
omit header not working on list pages

### ISSUE THREAD

**Issue by rwslippey** [budparr/gohugo-theme-ananke#265]
New to hugo but finding the theme to be great. One thing I can't figure out is omit_header_text: true does not work on _index.md or any other list page. (hopefully my lingo is correct here)

Works just fine on other pages no problem. Tried with the example site content as well and no dice. Is this functionality included or is it only for pages?

**Comment by rwslippey** [comment]
Ok, somebody is probably better at this than I but it didn't look like this was included in the features list. Here is what I did. Obviously moving site-header.html to my layouts folder to override the theme. I added modified it as such.
At Line two, under 
`{{ $featured_image := .Param "featured_image"}}` 
Add line 
' {{ if not .Params.omit_header_text }} `

Add the following to the end
`{{ else }}
  <header>
    <div class="{{ .Site.Params.background_color_class | default "bg-black" }}">
      {{ partial "site-navigation.html" . }}
    </div>
  </header>
  {{ end }}
`

Here is my complete file

`{{ $featured_image := .Param "featured_image"}}
{{ if not .Params.omit_header_text }}
{{ if $featured_image }}
  {{/* Trimming the slash and adding absURL make sure the image works no matter where our site lives */}}
  {{ $featured_image := (trim $featured_image "/") | absURL }}
  <header class="cover bg-top" style="background-image: url('{{ $featured_image }}');">
    <div class="{{ .Site.Params.cover_dimming_class | default "bg-black-60" }}">
      {{ partial "site-navigation.html" .}}
      <div class="tc-l pv4 pv6-l ph3 ph4-ns">
        <h1 class="f2 f-subheadline-l fw2 white-90 mb0 lh-title">
          {{ .Title | default .Site.Title }}
        </h1>
        {{ with .Params.description }}
          <h2 class="fw1 f5 f3-l white-80 measure-wide-l center mt3">
            {{ . }}
          </h2>
        {{ end }}
      </div>
    </div>
  </header>
{{ else }}
  <header>
    <div class="pb3-m pb6-l {{ .Site.Params.background_color_class | default "bg-black" }}">
      {{ partial "site-navigation.html" . }}
      <div class="tc-l pv3 ph3 ph4-ns">
        <h1 class="f2 f-subheadline-l fw2 light-silver mb0 lh-title">
          {{ .Title | default .Site.Title }}
        </h1>
        {{ with .Params.description }}
          <h2 class="fw1 f5 f3-l white-80 measure-wide-l center lh-copy mt3 mb4">
            {{ . }}
          </h2>
        {{ end }}
      </div>
    </div>
  </header>
{{ end }}
{{ else }}
  <header>
    <div class="{{ .Site.Params.background_color_class | default "bg-black" }}">
      {{ partial "site-navigation.html" . }}
    </div>
  </header>
  {{ end }}`

This looks to work for me. I can now disable the header text across all pages with omit_header_text: true. Hope this helps and if I've done something wrong please let me know... Always enjoy learning

**Comment by rwslippey** [comment]
Ok, somebody is probably better at this than I but it didn't look like this was included in the features list. Here is what I did. Obviously moving site-header.html to my layouts folder to override the theme. I added modified it as such.
At Line two, under
`{{ $featured_image := .Param "featured_image"}}`
Add line
`{{ if not .Params.omit_header_text }}`

Add the following to the end
```
{{ else }}
  <header>
    <div class="{{ .Site.Params.background_color_class | default "bg-black" }}">
      {{ partial "site-navigation.html" . }}
    </div>
  </header>
  {{ end }}
```
This is my complete site-header.html layout file.
```
{{ $featured_image := .Param "featured_image"}}
{{ if not .Params.omit_header_text }}
{{ if $featured_image }}
  {{/* Trimming the slash and adding absURL make sure the image works no matter where our site lives */}}
  {{ $featured_image := (trim $featured_image "/") | absURL }}
  <header class="cover bg-top" style="background-image: url('{{ $featured_image }}');">
    <div class="{{ .Site.Params.cover_dimming_class | default "bg-black-60" }}">
      {{ partial "site-navigation.html" .}}
      <div class="tc-l pv4 pv6-l ph3 ph4-ns">
        <h1 class="f2 f-subheadline-l fw2 white-90 mb0 lh-title">
          {{ .Title | default .Site.Title }}
        </h1>
        {{ with .Params.description }}
          <h2 class="fw1 f5 f3-l white-80 measure-wide-l center mt3">
            {{ . }}
          </h2>
        {{ end }}
      </div>
    </div>
  </header>
{{ else }}
  <header>
    <div class="pb3-m pb6-l {{ .Site.Params.background_color_class | default "bg-black" }}">
      {{ partial "site-navigation.html" . }}
      <div class="tc-l pv3 ph3 ph4-ns">
        <h1 class="f2 f-subheadline-l fw2 light-silver mb0 lh-title">
          {{ .Title | default .Site.Title }}
        </h1>
        {{ with .Params.description }}
          <h2 class="fw1 f5 f3-l white-80 measure-wide-l center lh-copy mt3 mb4">
            {{ . }}
          </h2>
        {{ end }}
      </div>
    </div>
  </header>
{{ end }}
{{ else }}
  <header>
    <div class="{{ .Site.Params.background_color_class | default "bg-black" }}">
      {{ partial "site-navigation.html" . }}
    </div>
  </header>
  {{ end }}
```


This looks to work for me. I can now disable the header text across all pages with omit_header_text: true. Hope this helps and if I've done something wrong please let me know... Always enjoy learning

**Comment by regisphilibert** [comment]
Yes the `omit_header_text` key is only used for Regular Page by default. In order to benefit from it on list pages  all you have to do though is copy/paste the `posts/list.html` file into your projects layouts directory and add this at the top:
```
{{ define "header" }}
  {{ partial "page-header" . }}
{{ end }}
```

Also, make sure you have `featured_image`  set on `/posts/_index.md`.
