### ISSUE TITLE
exampleSite/content translation

### ISSUE THREAD

**Issue by kaihendry** [budparr/gohugo-theme-ananke#269]
Perhaps related to https://github.com/budparr/gohugo-theme-ananke/issues/257

I see [metadata is translated](https://github.com/budparr/gohugo-theme-ananke/tree/master/i18n), but why not demonstrate an entire post in https://github.com/budparr/gohugo-theme-ananke/tree/master/exampleSite/content to exercise https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/partials/i18nlist.html IIUC

Found this theme with https://gohugo.io/getting-started/quick-start/ so this is my goto for learning Hugo templating.

Thanks!

**Comment by budparr** [comment]
Hi @kaihendry  Yes, I think what you're looking for is what we intend to do with #257. I'll close for now, but thank you for your vote for that feature.
