### ISSUE TITLE
Disqus is not showing comments for all of my posts

### ISSUE THREAD

**Issue by prabeesh** [budparr/gohugo-theme-ananke#271]
I am using **anake** theme for my personal blog. 

One of my post I have 58 comments [Install Apache Spark on Ubuntu-14.04](http://blog.prabeeshk.com/blog/2014/10/31/install-apache-spark-on-ubuntu-14-dot-04/) unfortunately the comments are not showing in the **disqus**. But for other posts with fewer comments are showing. Let me know is there any restrictions for the number of comments shown in **disqus**?

**Comment by budparr** [comment]
Hey, @prabeesh I'm not seeing any comments at all on your posts. Looks like this might be a DISQUS issue. Let me know what you come up with. If it looks like something specific to the theme, I'll have a look at our implementation to see if anything has changed.

**Comment by prabeesh** [comment]
[image: Screen Shot 2020-04-27 at 8.14.40 PM.png]
Please find the attached screenshot from Disqus UI.

**Comment by prabeesh** [comment]
Please find the screenshot from Disqus UI [screenshot](https://drive.google.com/file/d/1eWaoviZ-mFmNHVXc_5DncZS6mlIPihKx/view?usp=sharing). There you can find 58 comments, but it is not showing the Hugo page. Previously I was using Octopress for my blog and the comments were visible in the Octopress posts.

**Comment by budparr** [comment]
We'll check it out. Thanks for reporting. Can you point me to a post where there are comments showing (I'm not seeing any) and perhaps your repo?

**Comment by prabeesh** [comment]
You can refer to this [post](http://blog.prabeeshk.com/blog/2016/12/07/install-apache-spark-2-on-ubuntu-16-dot-04-and-mac-os/) to see the Disqus comments and  find the repo [here](https://github.com/prabeesh/prabeesh.github.io/tree/source)

**Comment by budparr** [comment]
Did you change the URL of the post? As best as I can tell this is a DISQUS issue, not an issue with the theme. The post references 59 comments, but those have a different slug. I'm not really sure how DISQUS works, but maybe that's it.

**Comment by prabeesh** [comment]
Thank you @budparr I will have to check the URL slug.

**Comment by prabeesh** [comment]
The issue has been fixed. I have updated the URL slug for the posts. Thank you @budparr for the inputs.
