### ISSUE TITLE
RSS svg icon

### ISSUE THREAD

**Issue by NRKirby** [budparr/gohugo-theme-ananke#278]
I love this theme, thank you!

Would it be possible to get an RSS svg icon? I would like one next to my Twitter icon! I see there are 13 social rss icons and I'm thinking having an RSS icon is something a lot of people might want..

Thanks again,  Nick

**Comment by budparr** [comment]
Sure thing.

We can use this icon https://material.io/resources/icons/?search=rss&icon=rss_feed&style=baseline
