### ISSUE TITLE
search do not work (extra slash)

### ISSUE THREAD

**Issue by thierrybo** [budparr/gohugo-theme-ananke#280]
Hi,

as you can see on the demo site https://themes.gohugo.io/theme/mainroad/
if you search `pectoribus` there is no result because the search string is
`pectoribus site:https://themes.gohugo.io//theme/mainroad/`
instead of 
`pectoribus site:https://themes.gohugo.io/theme/mainroad/`

**Comment by budparr** [comment]
Hi @thierrybo I don't understand what your issue has to do with the Ananke theme. Can you explain?

**Comment by thierrybo** [comment]
is it not the AnaNke theme that generates the url to search for google?

**Comment by budparr** [comment]
The link you're pointing to is not Ananke, no, and it's not related to themes.gohugo.io
