### ISSUE TITLE
Eliminate top image shading

### ISSUE THREAD

**Issue by prdm0** [budparr/gohugo-theme-ananke#289]
Dear, 

how to lighten the shading of the image that goes at the top of the page? I would like it to be close to the brightness and contrast original.

King regards,
@prdm0

**Comment by budparr** [comment]
@prdm0 Did you figure this out, or do you still need help? It can sometimes takes a bit of time to work through issues here.

**Comment by prdm0** [comment]
@budparr, thanks for responding. I solved the problem and ended up preferring the standard. I'm currently having trouble highlighting the code using **highlight.js**. See issues #292 . Are there any predictions of the theme for providing this support by default?

Kind regards,
@prdm0 .

**Comment by h3ndrik** [comment]
for reference... you can add something like this to your config.toml:

```
[params]
  cover_dimming_class = "bg-black-10"
```
