### ISSUE TITLE
Add support to highlight.js

### ISSUE THREAD

**Issue by prdm0** [budparr/gohugo-theme-ananke#292]
Dears,

how can I add support for **highlight.js**? I tried to follow [these](https://amber.rbind.io/2017/11/15/syntaxhighlighting/) steps but to no avail.

Kind regards,
@prdm0.

**Comment by prdm0** [comment]
Add the code below at the top of the **page-header.html** file:

```
<link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.0/styles/night-owl.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.0/highlight.min.js"></script>
 <script>hljs.initHighlightingOnLoad();</script>
```

**Comment by budparr** [comment]
Thanks for including your solution here for others.

**Comment by prdm0** [comment]
@budparr , see how it was clicking [here](https://prdm0.rbind.io/post/workshop-paraibano-de-estat%C3%ADstica-2020/). The code is at the bottom of the page.
Just add the code below in page-header.html:

```html
<link href="//cdn.bootcss.com/highlight.js/10.1.0/styles/default.min.css" rel="stylesheet">
<script src="//cdn.bootcss.com/highlight.js/10.1.0/highlight.min.js"></script>
<script src="//cdn.bootcss.com/highlight.js/10.1.0/languages/r.min.js"></script>
<script>
hljs.configure({languages: []});
hljs.initHighlightingOnLoad();
</script>
```

For those who program in a different language of R, just change `r.min.js` for `language.min.js`, where `language` is the language of interest. If you want another theme, just change `default.min.css` to `theme.min.css`, in which `theme` you will change to the desired theme. For example, to use **dracula** and python language:

```html
<link href="//cdn.bootcss.com/highlight.js/10.1.0/styles/dracula.min.css" rel="stylesheet">
<script src="//cdn.bootcss.com/highlight.js/10.1.0/highlight.min.js"></script>
<script src="//cdn.bootcss.com/highlight.js/10.1.0/languages/python.min.js"></script>
<script>
hljs.configure({languages: []});
hljs.initHighlightingOnLoad();
</script>
```

It would be interesting to provide this support in **config.toml**. The user could choose the language and the theme.

A list of all supported themes and languages can be found [here](https://highlightjs.org/static/demo/).

Kind regardsm
@prdm0.
