### ISSUE TITLE
Add sub section list to list pages

### ISSUE THREAD

**Issue by peter-jerry-ye** [budparr/gohugo-theme-ananke#300]
Hello, I'd like to organize my blog something like this

- travel / china / xxx
- travel / france / xxx
- projects / java / xxx
- projects / scala / xxx

So I would like to have multiple level of sections, where each index.md can display its subsections. 
Is it possible to add this feature? Thanks

**Comment by budparr** [comment]
Hi @peter-jerry-ye Hugo respects your folder section out of the box, so I don't believe you need the theme to do anything special for you here. You might get more help in the Hugo forums on non-theme questions. I'll close, but feel free to open if you have more information.

**Comment by peter-jerry-ye** [comment]
Hi @budparr , 
I do understand that Hugo handles well the folder section. What I don't understand is how we can get access to subsections from its parent. I mean, I could put a menu on the whole, but what if I want to present the subsections on the page of parent section? For example, in the section 'Travel' (which is not home page), I'd like to present basic information for each country I've visited, and then each country is a section that contains many posts.
I've looked around and it seems that no theme has ever done this, so I'm not sure if it was I that had a bad design or misunderstood something. Could you help me? I can modify the list.html to achieve this easily, but I just wonder why no one has ever done this before.
Thanks.

**Comment by budparr** [comment]
@regisphilibert Might have ideas, but otherwise the forum is where you're likely to find a variety of opinions.
