### ISSUE TITLE
How to change the height of the header image?

### ISSUE THREAD

**Issue by zzamboni** [budparr/gohugo-theme-ananke#41]
Hi @budparr,

I've been playing with Hugo+Ananke, and I really like it. I do have one question: is there an easy way to resize the header? I would like to make it a bit shorter so it doesn't take up so much space. I gather that it should be possible by reconfiguring some CSS parameter, but I'm not fluent enough to figure it out.

Thanks in advance, and thanks for your work on the theme!

**Comment by budparr** [comment]
Hey, @zzamboni  - If you duplicate the header file in your root (so you don't have to change anything on the the theme) you can change the padding on the content in the header (which is what makes it the size that it is). 

So for example, change `pb3-m pb6-l` to whatever suits you (`pb2` ?) here: https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/partials/page-header.html#L6 

Hope that helps. Let me know if not.

**Comment by zzamboni** [comment]
@budparr indeed it helped - thanks! Your pointer got me looking in the right direction and I've finally started to figure out the effects the different classes have. In case anyone else comes looking, this page has helped me a lot: http://tachyons.io/docs/table-of-styles/

**Comment by budparr** [comment]
That's awesome. I'll put a note about this in the readme.

**Comment by nicelifeBS** [comment]
@budparr I tried those steps which you describe but the header just stays the same. Do I need to install the packages and run which are described here: https://github.com/budparr/gohugo-theme-ananke/blob/master/src/readme.md?

**Comment by budparr** [comment]
Hey, @nicelifeBS The above should work without any further processing. Maybe @zzamboni can let us know what he changed.

**Comment by zzamboni** [comment]
@nicelifeBS you can find the full source for [my website](http://zzamboni.org) at https://github.com/zzamboni/zzamboni.org/. The file I had to change to make the header shorter is https://github.com/zzamboni/zzamboni.org/blob/master/layouts/partials/site-header.html. You can compare it to the version from the theme (at https://github.com/zzamboni/zzamboni.org/tree/master/themes/gohugo-theme-ananke) to see what changed. In this particular case:

```diff
diff layouts/partials/site-header.html themes/gohugo-theme-ananke/layouts/partials/site-header.html 
5c5
<   <header class="cover bg-center" style="background-image: url('{{ $featured_image }}'); ">
---
>   <header class="cover bg-top" style="background-image: url('{{ $featured_image }}');">
8,9c8,9
<       <div class="tc-l pv4 ph3 ph4-ns">
<         <h1 class="f2 f-subheadline-l fw2 white-90 mb0 mt0 lh-title">
---
>       <div class="tc-l pv4 pv6-l ph3 ph4-ns">
>         <h1 class="f2 f-subheadline-l fw2 white-90 mb0 lh-title">
```

Keep in mind that the version of Ananke I'm using is a bit old (around August 2017), I haven't upgraded since I have quite a few customizations, so some things may have changed if you are using a more recent version.

Hope this helps.

**Comment by nicelifeBS** [comment]
Ah thank you guys. Was my mistake. I was looking in page-header.html and not site-header-html. All good here.

**Comment by matt-sharp** [comment]
I've tried making the changes suggested above but I think something has changed in the source code since the above was posted.
Please can anyone help me to understand what I need to change?
Here's a link to the site header file on my Github repo:

[site-header.html](https://github.com/mullet1989/lauristonrunners/edit/main/layouts/partials/site-header.html)
