### ISSUE TITLE
table of contents: toc = true - please add support

### ISSUE THREAD

**Issue by mbana** [budparr/gohugo-theme-ananke#42]
hi,

please add support for this.

```sh
mbana-mb:cv mbana$ ll
total 24K
drwxr-xr-x 2 mbana staff  170 Aug 22 15:07 .
drwxr-xr-x 5 mbana staff  204 Aug 22 15:01 ..
-rw-r--r-- 1 mbana staff  577 Aug 22 15:07 _index.md
-rw-r--r-- 1 mbana staff 1020 Aug 22 15:11 cover-letter.md
-rw-r--r-- 1 mbana staff  13K Aug 22 15:10 resume.md
```

in `resume.md` i want all the headings to show up on the right-hand side of the page. currently it only lists the other pages in the same directory.

Thanks a lot,

**Comment by budparr** [comment]
Good idea. I'll try to look soon, and if you want to accomplish this now, you could duplicate this template into your root folder and overwrite it there: https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/partials/menu-contextual.html

So, in your site, it would be making a copy from:
`themes/gohugo-theme-ananke/layouts/partials/menu-contextual.html`
to here:
`layouts/partials/menu-contextual.html`

**Comment by zzamboni** [comment]
@mbana I recently dealt with this - if you want to take a look, here's the simple toc.html file I'm using at my website zzamboni.org: https://github.com/zzamboni/zzamboni.org/blob/master/layouts/partials/toc.html. I'm using the builtin .TableOfContents, processing it to show up on the right-hand on a similar style to the "other posts" box.

**Comment by budparr** [comment]
I think this is a good idea, and a good opportunity to use some Hugo native functionality. I'm working on a new version of the theme and will include a provision for this. Thanks for your patience, I've been swamped lately.

**Comment by budparr** [comment]
This is now added. Thanks!
