### ISSUE TITLE
Changing width of content?

### ISSUE THREAD

**Issue by zo0o0ot** [budparr/gohugo-theme-ananke#46]
I'm a bit of a newbie with hugo, but I can't figure out how to modify the width of the default content in your theme.

I see the layout here: https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/_default/single.html

It's my understanding that I'd override the layout in `/layouts/_default/single.html`.

My goal is to provide more width by default in order to embed Tableau Public charts.

An example of my test embed is here:  https://leagify.github.io/quicktest/posts/my-first-post/

Any help you are willing to provide is appreciated.

**Comment by budparr** [comment]
Hey @zo0o0ot In this line: https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/_default/single.html#L4 Remove `mw7` and that should work for you. Let me know if that's not what you're looking for.

And, here's the max width settings in Tachyons, which you might find helpful as well. https://github.com/tachyons-css/tachyons/blob/master/src/_max-widths.css

**Comment by zo0o0ot** [comment]
This seemed to solve the issue.  I'll let you know if I run into anything else.
