### ISSUE TITLE
ERROR: [...] template.go:495: Failed to add template

### ISSUE THREAD

**Issue by saljut7** [budparr/gohugo-theme-ananke#47]
Hi, 

wanted to try HUGO following https://gohugo.io/getting-started/quick-start/ but get

```
$ hugo server -D
Started building sites ...
ERROR: 2017/09/19 10:05:46 template.go:495: Failed to add template theme/partials/site-footer.html in path /home/USERNAME/hugotest/themes/ananke/layouts/partials/site-footer.html: template: theme/partials/site-footer.html:4: function "now" not defined
ERROR: 2017/09/19 10:05:46 template.go:529: template: theme/partials/site-footer.html:4: function "now" not defined
ERROR: 2017/09/19 10:05:46 general.go:236: theme/partials/site-footer.html is an incomplete or empty template
Built site for language en:
0 draft content
0 future content
0 expired content
1 regular pages created
2 other pages created
0 non-page files copied
1 paginator pages created
0 tags created
0 categories created
total in 40 ms
Watching for changes in /home/USERNAME/hugotest/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
^C
```

I work with HUGO version provided by Debian 9.1:

```
$ hugo version
Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-30T17:01:10+01:00
```

Is the stable repository version of HUGO to old to work with HUGO standard template?

Thx
sj7

**Comment by budparr** [comment]
Hey, @saljut7 I'll check this out today.

**Comment by budparr** [comment]
Hey, @saljut7 I'm sorry I could have helped you more easily had I just looked closer at the issue when you dropped it (I've been in middle of a big site launch). The Hugo version you have there is quite out of date. Hugo is currently on `.27.1` and I recall that the way `now` is handled is new from a few versions back. I don't use Debian, but from the docs it looks like you can use the Snap package to get a more up-to-date version. http://gohugo.io/getting-started/installing/#linux

Hope that helps! I'm going to close this for now, but feel free to jump in and let me know if you have other issues.

**Comment by saljut7** [comment]
THx @budparr it works using snap. :)
