### ISSUE TITLE
Contact form complains about invalid email address after page has been loaded

### ISSUE THREAD

**Issue by digitalcraftsman** [budparr/gohugo-theme-ananke#5]
The contact form shows the error message "Must be a valid email address." even if no email address was entered yet.

**Comment by budparr** [comment]
So you just mean the copy below the field, right? Yeah, I should make that more usable. I only had it in as an example of a comment (in another instance of the form I use that as a hidden validation message, hence that wording).

**Comment by digitalcraftsman** [comment]
> So you just mean the copy below the field, right?

Exactly

**Comment by budparr** [comment]
So, I fixed that, thank you. I changed the copy to make sense.
