### ISSUE TITLE
Blog Featured Image stopped working

### ISSUE THREAD

**Issue by mirontoli** [budparr/gohugo-theme-ananke#516]
Hi, I have used ananke theme since December 2021. Now when I updated it, my featured image stopped working. 

The current code (not working) is https://github.com/theNewDynamic/gohugo-theme-ananke/tree/8fdfd205f9b4fd2f52eac9dfd2da8e11bea2015e

The previous working code was https://github.com/theNewDynamic/gohugo-theme-ananke/tree/c7b9901e01ec3720b47fcef3d33bdbd6ce53f000

My featured image is defined in config.toml (nothing changed since that day): 

```
[params]
  ...
  featured_image = "https://ik.imagekit.io/mirontoli/bridge_UngKtedn3OP.jpg?updatedAt=1639597203043"
```

**Comment by mirontoli** [comment]
I am using Ananke as a git submodule (right or wrong). I suppose you recommend using Hugo Module. I'll take look into it and the cascade configuration. Thank you very much for pointing me in right direction.

**Comment by regisphilibert** [comment]
I find it much more easier to use Hugo Module indeed, but to each his own. As a maintainer, I often push changes to master that might introduce breaking changes, but the only way I can communicate with the users about those potential breaking changes is using release notes, so I like the fact that the default Hugo Module update command will use the latest release (whose notes documents changes etc...)
