### ISSUE TITLE
Code formats without line breaks

### ISSUE THREAD

**Issue by carmenbianca** [budparr/gohugo-theme-ananke#56]
See

![ekrankopio de 2017-10-05 17-42-43](https://user-images.githubusercontent.com/12065945/31236620-e8964de2-a9f4-11e7-8a84-6e5584c1a8c0.png)

See also https://github.com/carmenbianca/gohugo-theme-ananke/commit/395981a3e672f88bca2eeaad3f343f48b22418ca

I'm not quite sure what's wrong though. Copy+pasting the raw HTML formats it correctly, so there's probably something in the CSS, maybe.

**Comment by wikty** [comment]
Maybe, there is a bug in CSS `themes/ananke/static/dist/main.css`. `pre code` is set as `white-space:normal;` . I think `white-space:pre;` is correct.

**Comment by budparr** [comment]
I'll try to check this out today. Oddly enough I rarely, if ever, write code blocks in my posts, so this is a lacuna for me.

**Comment by niconoe** [comment]
+1: got the same problem (with HTML code using the highlight sorthcode), and indeed changing `white-space` from `normal` to `pre` seems to solve the issue.

I wanted to properly test everything to submit a pull request, but I'm not sure of how to properly build the CSS.. Should I call Postcss-cli directly? It would be great if you could give us some build instructions - it may even be a good opportunity to add a `contributing` section in the documentation.

thanks for the great work!

**Comment by budparr** [comment]
Hey, @niconoe Does this help? https://github.com/budparr/gohugo-theme-ananke/tree/master/src

If you cd into the source folder (and yarn install), `npm run build:production` will do it.

**Comment by niconoe** [comment]
Thanks a lot, I missed that README file.

**Comment by budparr** [comment]
Thanks everyone, and thanks @niconoe for the contribution!
