### ISSUE TITLE
[webpack] Hash assets

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo-theme-ananke#60]
This will improve performance.
- [ ] Set up dev only webpack config

**Comment by illycz** [comment]
Is it possible to rev all assets within Hugo?
1. In HTML (images, fonts, files)
2. In CSS (bg images)

Thanks for clarification...

**Comment by budparr** [comment]
Hey, @illycz I'm sorry, I don't understand what you're asking.

**Comment by illycz** [comment]
Assets revisioning (hash edited assets for cache busting).

Thanks

**Comment by budparr** [comment]
For that you might want to look at Netlify's Victor Hugo starter.

**Comment by illycz** [comment]
I'm looking for solution which uses default Hugo structure because I want to use https://forestry.io/ for administration purpose. And they support only default install I think: https://forestry.io/docs/developing-with-hugo/asset-pipeline/

**Comment by illycz** [comment]
Maybe something like this: https://www.hughgrigg.com/posts/gulp-asset-versioning-hugo-data-files/

**Comment by budparr** [comment]
Maybe. Forestry has a Slack and I'd bet you get some info from the team there.
