### ISSUE TITLE
How do I make a menu item have a different background and text color?

### ISSUE THREAD

**Issue by ctindel** [budparr/gohugo-theme-ananke#633]
My site is for a non-profit and I'd like the last menu item to be a donate link that has a different background and text color so it stands out from the rest of the menu.  

Is there a good way to do this?

**Comment by dryscord** [comment]
Add a `params class` to that menu item that you can target with CSS. See the [example here](https://gohugo.io/content-management/menus/#example-front-matter). Then in your menu code you add something like `<a href="" class="{{ .Params.class }}"</a>` then  target that class with CSS.
