### ISSUE TITLE
Parmeterize number of recent posts.

### ISSUE THREAD

**Issue by DeveloperDavo** [budparr/gohugo-theme-ananke#68]
Hello, 

I think it would be nice to parameterize the number of recent posts to display in `index.html` instead of hardcoding to `3` in `{{ range (first 3 $section) }}`. Something like:
```
[params]
  recent_posts_number = 5  
```
in `config.toml` to replace `3` in `index.html`.

Let me know if you would like me to submit a pull request for this.

Thanks,

David

**Comment by budparr** [comment]
Sure, that's a great idea. PR is welcome!

**Comment by budparr** [comment]
solved in #69
