### ISSUE TITLE
linkedin icon is almost invisible on dark background

### ISSUE THREAD

**Issue by martin-weber** [budparr/gohugo-theme-ananke#70]
Is it possible to invert the linkedin icon, so that it is visible like the other icons on dark backgrounds?

**Comment by budparr** [comment]
Hey, @martin-weber Can you put up a screenshot, or point me to a website? I think I have a good solution for this.

**Comment by martin-weber** [comment]
The background is an image of a skyline at night.

This is the screenshot without hover:
<img width="521" alt="bildschirmfoto 2017-11-06 um 23 11 31" src="https://user-images.githubusercontent.com/14039505/32466658-fa19cc12-c347-11e7-8305-7501b04fac3c.png">

This is the screenshot with mouse hover.
<img width="498" alt="bildschirmfoto 2017-11-06 um 23 11 57" src="https://user-images.githubusercontent.com/14039505/32466661-fc3a9f12-c347-11e7-9164-3afe8dca67d9.png">

**Comment by martin-weber** [comment]
What I've seen as well is that the _social-icons.css file does not contain linkedin-class in the first line.

`.facebook, .twitter, .instagram, .youtube, .github {
  fill: #BABABA;
}`

**Comment by budparr** [comment]
Yeah, sorry about that. The linkedin came through in a PR and I guess I wasn't thorough in my review. I'm going to see if I can fix it up right now.

**Comment by martin-weber** [comment]
Thank you. 
I like this template.

**Comment by budparr** [comment]
Should be fixed now. Thanks for bringing it to my attention, @martin-weber
