### ISSUE TITLE
Figure size

### ISSUE THREAD

**Issue by barthac** [budparr/gohugo-theme-ananke#79]
Hi, 
Does ananke impose a width on all figures and if so, is there a way to override this? I tried using 
{{< figure src="/images/furnace.jpg" width="500px">}} within one of the .md files.
But this doesn't change the figure size.

I also tried just saving the figures as a smaller size, but hugo just enlarges them to keep them the same size (just lower resolution).

Please advise how I can change the figure size!

Thanks!

**Comment by budparr** [comment]
Hi @barthac I believe we're just using the Hugo internal shortcode for this, so I'd probably do a search over there: https://github.com/gohugoio/hugo

**Comment by rshillington** [comment]
@barthac i realize it's been a while since your initial question but I'm running into the same issue and I'm wondering if you did get a solution.  I'm trying to get images with text that flows around but no luck.

**Comment by budparr** [comment]
You can use Hugo's [shortcode](https://gohugo.io/content-management/shortcodes/#use-hugo-s-built-in-shortcodes) and add a class to it:

The class `fl` should already work in an Ananke site:

```
{{< figure src="/uploads/image-name.jpg" class="fl" >}}
```
Tachyons offers some width and margin classes that should be available to you as well.
