### ISSUE TITLE
image alignment

### ISSUE THREAD

**Issue by barthac** [budparr/gohugo-theme-ananke#80]
Hi,
When including two figures in a page, is there a way to get them to appear side by side instead of sequentially? It is my understanding from reading the main hugo pages that this should happen naturally if the lines are written with no space between them:

![screen shot 2018-02-03 at 3 17 38 pm](https://user-images.githubusercontent.com/21955716/35771126-a5afc228-08f5-11e8-84da-5dd89218b58a.png)

But they appear one after the other. Is there a way to override this?

Thanks!

**Comment by budparr** [comment]
This is more of an HTML question, but you could give them a style of `display: inline-block`
