### ISSUE TITLE
Site logo

### ISSUE THREAD

**Issue by Tim-Butterfield** [budparr/gohugo-theme-ananke#81]
It would be nice to include support for a site logo image parameter.  One possibility might be a modification to the BaseURL link in site-navigation.html like this:

```
    <a href="{{ .Site.BaseURL }}" class="f3 fw2 hover-white no-underline white-90 dib">
      {{ if .Site.Params.logo }}
      <img src="{{ .Site.Params.logo }}" class="v-mid" />
      {{ end }}
      {{ .Site.Title }}
    </a>
```

**Comment by budparr** [comment]
I'm going to do some work on the theme this week and this shouldn't be too hard to add. Thanks, @Tim-Butterfield

**Comment by kentmz** [comment]
I'd love to see this feature to add a logo.
