### ISSUE TITLE
Unable to change hero image

### ISSUE THREAD

**Issue by Allen616** [budparr/gohugo-theme-ananke#90]
So sorry to bother you. Without any success I have been trying to trouble shoot why I am unable to change the hero image on my deployment.

 [My repo with ananke](https://github.com/citizenlabsgr/homepage-v2)

At most I get a dark grey background instead of the hero image with the gargoyle. I have made changes to config.toml and featured image for content/_index.md without any luck.

Thank you very much for your help.

**Comment by budparr** [comment]
Hey, @Allen616 It looks like they image you put in your front matter is:
`hero-light-festival.jpg'
and the image you put in your images directory is:
`hero-light-festival.jpeg`

Note the difference in extension.

Cheers!

**Comment by Allen616** [comment]
Many thanks. Apologies for the simple error.
