### ISSUE TITLE
body width

### ISSUE THREAD

**Issue by LyzardKing** [budparr/gohugo-theme-ananke#91]
Hi!
I'm using this theme to build a website, and I have an issue with the body width.
If in the page I only have a google form embedded, with the width set to 100% it'll show up very thin and centered.
I'm having the same issue with https://github.com/liwenyip/hugo-easy-gallery
If there's something with a fixed dimension in the page it works, otherwise it's not even visible

**Comment by LyzardKing** [comment]
It's fixed (sort of...) if I remove "flex-l" from layouts/_default/single.html, from:
`<div class="flex-l mt2 mw8 center">`

**Comment by budparr** [comment]
Hi @LyzardKing I think you got it right. I'm revisiting the templates soon and will keep that issue in mind. Thanks!

**Comment by budparr** [comment]
It's a node_module that's imported when I build the CSS file. You can see the docs here: http://tachyons.io/docs/layout/flexbox/

The other issue `mw8` which puts a max-width on the body. You can remove that, too.
