### ISSUE TITLE
Set default for params.recent_posts_number

### ISSUE THREAD

**Issue by paskal** [budparr/gohugo-theme-ananke#92]
$subj, without setting this variable no posts shown on main page.

**Comment by budparr** [comment]
Hi. @paskal I'll look at this this evening. Thanks!

**Comment by budparr** [comment]
Hi @paskal This appears to be set: `{{ $n_posts := $.Param "recent_posts_number" | default 3 }}`

https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/index.html#L23

Let me know if I'm looking at the something other than what you're referring to.

**Comment by paskal** [comment]
You're right, my bad! I guess I was looking in some wrong place during the test.
Soon I'll post a highlight of a few blogging hugo themes and your is included, I'll notify you when it will be published. Thanks for the great theme!

**Comment by budparr** [comment]
No worries. Thanks very much - looking forward to seeing that.

**Comment by paskal** [comment]
I'm not sure github sent notifications to mentioned authors, so posting double there: theme highlight is out, this very theme is in it, additional info on https://github.com/paskal/terrty/issues/1.
