### ISSUE TITLE
Deployment question - content loading, but not scripts or css

### ISSUE THREAD

**Issue by RyanTG** [budparr/gohugo-theme-ananke#93]
Sorry, this is such a basic question. I've used Hugo just fine on another site. But I'm having trouble with this theme.

Can you just verify that I'm deploying this correctly? I know this is hugo 101...

````
hugo -t gohugo-theme-ananke
git add .
git commit -m "whatever"
git push origin master
````

When loading the website, nothing is fetched aside from the content (like, no js or css). And the content takes a good minute to load.

Perhaps something is wrong with my server...

**Comment by budparr** [comment]
It looks like you have two different things there. First your running Hugo, then you're adding your site to a git repository. Those two processes are separate. So before you run Hugo, set up your repo (as you've done with your git commands), then you have to download the theme, so if you haven't done that: 

`git clone https://github.com/budparr/gohugo-theme-ananke.git themes/gohugo-theme-ananke`

**Comment by RyanTG** [comment]
I have the theme downloaded, and it's working beautifully on my local.

I removed the .git folder from the theme, so I don't have to worry about submodules.

Does the running part look like the correct command to use the theme? 

I've modified the theme (and moved those edited files out of the theme and into partials.

**Comment by budparr** [comment]
What are using for deployment? Are you building locally and sending the files somewhere, or is a continuous integration service building for you? If you're building locally it looks like that command should work (you can also put it in your config).

**Comment by RyanTG** [comment]
I'm building locally, and then sending the files.

I just ran `npm run build:production` thinking that might be needed to build the src files, since the network monitor is showing that `main.css` and `app.bundle.js` aren't loading. But then again, those two files were already in /public/ - plus, I can access them directly on the website. Dunno why they won't load!

This smells like a server issue to me...

**Comment by RyanTG** [comment]
Thank you. I resolved it. I had `https` in the config, but server was only listening for `http`. 

Blah! :)

**Comment by budparr** [comment]
It's always something small like that. Happens to me all the time. By the way, you might want to check out some of the deployment options like Netlify. They really do all the work for you and have  a generous free tier.
