### ISSUE TITLE
Remove theme directory name hard-coding

### ISSUE THREAD

**Issue by kaushalmodi** [budparr/gohugo-theme-ananke#95]
This issue was brought up in https://github.com/gohugoio/hugoDocs/pull/443.

Technically, any theme can be cloned to any directory name. Dependency on the original theme name could break some functionality as evident in that PR. 

I understand the reason why readDir and hardcoded dir name is used in this instance. 

Though, it should be possible to avoid that. 

/cc @BrianH2

**Comment by budparr** [comment]
@kaushalmodi Did you say you have a solution? I'm all ears 👂

**Comment by budparr** [comment]
Thanks for your help, @kaushalmodi I figured out a similar solution using Webpack. I appreciate you pointing me in the right direction.

**Comment by kaushalmodi** [comment]
Webpack is still alien to me, though I see that that is automating that .json file generation, very cool! Glad I could help :)

**Comment by budparr** [comment]
Webpack will solve "all" of your problems :)
