### ISSUE TITLE
Hugo fails to load CSS and Javascript files without baseURL

### ISSUE THREAD

**Issue by anddongyangli** [budparr/gohugo-theme-ananke#97]
Hugo fails to load the assets in debug mode when the `baseURL` is set to something like `"https://example.com/hugo/"`. A 404 page appears when accessing the css or Javascript file directly via the web browser.

We might want to set absolute URLs for these assets based on the configured `baseURL`.

Thanks.

**Comment by budparr** [comment]
Thanks for pointing this out, @anddongyangli I'll check it out.

**Comment by anddongyangli** [comment]
@budparr  Thanks for addressing this issue.

This issue still exists if the baseURL contains a non-root context path.
For example,  set the `baseURL` in  the configuration file like this:
```

baseURL = "http://www.foobar.com/blog"
```

Starting hugo server in debug mode, the following code
```go
 {{ $script := .Site.Data.webpack_assets.app }}
{{ with $script.js }}
  <script src="{{ absURL (printf "%s%s" "/dist/" .) }}"></script>
{{ end }}
```
will be compiled to
```
<script src="http://localhost:1313/dist/js/app.3fc0f988d21662902933.js"></script>
```
instead of 
```
<script src="http://localhost:1313/blog/dist/js/app.3fc0f988d21662902933.js"></script>
```

I tried with the following code, it works fine.

```go
{{ $script := .Site.Data.webpack_assets.app }}
{{ $baseURL := .Site.BaseURL }}
{{ with $script.js }}
    <script src="{{ printf "%s%s%s"  $baseURL  "/dist/" . }}"></script>
{{ end }}

```

**Comment by anthonyfok** [comment]
Thanks @anddongyangli!  But the fix is simpler: simply removing the leading slash, i.e. changing "/dist/" to "dist/" would do the trick because absURL already takes the baseURL into consideration when it sees a relative path.

On second thought, maybe relURL would work just as well.
